### ISSUE TITLE
Launch Problem

### ISSUE THREAD

**Issue by NjbSyd** [HozefaRizvi/TICK-TACK-TOE-GAME#1]
Why not launch it on some free hosting service.
So users can test it directly without having the trouble of downloading and setting up the files..

**Comment by HozefaRizvi** [comment]
Najeeb you're right. I can upload this on free hosting sites but you think they are secure enough? 
I've uploaded this in this way because people will also see the code and make changes in the code rather than only watching the game running in browser.... 
Next time I will also launch it on free hosting site and provide code files also. :)

**Comment by NjbSyd** [comment]
People can browse Source code here in this repo.
And you can provide a link in ReadMe.md file so, visitors can test it on the go.

**Comment by HozefaRizvi** [comment]
ok that's a great idea I will do this from now onwards
